- proto/google/events/cloud/storage/v1/events.proto
The field numbers are intended to be high enough to avoid conflicts
with new API fields.
Note that "kind" is not included here, as it's not expected to be
useful.
Part of addressing #6
> Add fields which are in existing JSON, but not the API proto

- proto/google/events/cloud/scheduler/v1/events.proto
Reason: we will put time in standard CE time attribute.
> Remove execution time from scheduler schema

- proto/google/events/cloud/pubsub/v1/events.proto
This corresponds to the JSON received for push notifications. In GCF
events, there is no indication of the subscription; only the message
is received as the event data. This means we cannot convert from the
GCF format to the CloudEvent format.
cc @yolocs @hrasadi
> Add the "wrapper" around the PubSub message

- proto/google/events/cloud/storage/v1/data.proto
It's a BoolWrapper in the API to allow the distinction between
"false", "true" and "unset" for the purpose of inheriting values
from the bucket on object creation. This is unnecessary for event
consumption.
Fixes #6.
> Change the Storage event_based_hold field to bool

- proto/google/events/cloud/firestore/v1/data.proto
This doesn't affect the JSON representation at all, but we might as
well match internal proto field numbers where possible - it may have
advantages in the future if we want to deliver proto binary
representations of events.
> Update Firestore event data proto to match internal field ordering

- proto/google/events/cloudevent.proto
While the field number here *should* be valid, it at least causes
problems in C#. I'll investigate whether this is a Google.Protobuf bug
separately, but it does no harm to use a smaller number here.
> Use a smaller extension field number for the cloud_event_type

- proto/google/events/cloud/firestore/v1/data.proto
Internal discussions suggest this shouldn't be part of the event
data. (It isn't part of the payload in GCF events; it's provided
as a separate field in the root of the event body.) Client libraries
can provide manually-written code to parse document names instead.
Philosophically, this isn't part of the underlying event - it
depends on the event subscription (which contains the resource
template being used).
Cc:
- @yolocs (Events)
- @mbleigh (Firebase)
- @hrasadi (Events)
- @fredzqm (Firebase)
> Remove "wildcards" from Firestore document event data

- proto/google/events/cloud/storage/v1/data.proto
- Media/self link comments were the wrong way round
- Add the "kind" field for completeness - it will always have the same value, but it *is* part of the REST resource model
I have *not* included custom_time (despite it being in the Discovery doc) as I believe aspects of this are still in flux.
> Fix: Storage object improvements

- README.md
- testdata/README.md
- testdata/google/events/cloud/firestore/v1/DocumentEventData-complex.json
- testdata/google/events/cloud/firestore/v1/DocumentEventData-simple.json
- testdata/google/events/cloud/pubsub/v1/MessagePublishedData-binary.json
- testdata/google/events/cloud/pubsub/v1/MessagePublishedData-text.json
- testdata/google/events/cloud/storage/v1/StorageObjectData-simple.json
(Only the last commit is new - the rest is based on #48.)
This is sample data that can be used by code in language-specific repos to validate the schema. Once we've got the relevant bits in place (the data and the code to validate it) we can add it as a continuous integration check.
This is one part of addressing #50.
See https://github.com/googleapis/google-cloudevents-dotnet/pull/30/files for the corresponding code to test this with .NET. (Ideally we should have something similar in every language.)
> Sample data for validation

- README.md
- proto/google/events/cloud/audit/v1/data.proto
- proto/google/events/cloud/audit/v1/events.proto
- testdata/google/events/cloud/audit/v1/LogEntryData-pubsubCreateTopic.json
- third_party/googleapis/README.md
- third_party/googleapis/google/api/monitored_resource.proto
(Replaces the prototype in #47.)
This is ready for review, but we should dig more carefully to work out how to answer the questions in the second commit.
This PR does *not* include anything that will interpret the `@type` field that is emitted as a byproduct of the `Any` field.
> Wrap Cloud Audit Logs in a LogEntry proto

- README.md
- proto/google/events/cloud/cloudbuild/v1/data.proto
- proto/google/events/cloud/cloudbuild/v1/events.proto
This makes the proto structure match the event type.
(The duplication of "cloud" in the name has been discussed
separately.)
cc @yolocs. @capri-xiyue
> fix: Move the CloudBuild events under google.events.cloud.cloudbuild

- tools/quicktype-wrapper/README.md
- tools/quicktype-wrapper/package-lock.json
- tools/quicktype-wrapper/package.json
- tools/quicktype-wrapper/src/index.ts
Adds CLI flags to quicktype tool
Tested locally.
```
qt \
--in /Users/timmerman/Documents/github/googleapis/google-cloudevents/proto/ \
--out /Users/timmerman/Documents/github/googleapis/google-cloudevents-nodejs/src
***********************
** Quicktype Wrapper **
***********************
* Valid Languages (L): csharp,java,python,rust,crystal,ruby,golang,cplusplus,elm,swift,objective-c,typescript,javascript,kotlin,dart,pike,haskell
***********************
* Config:
- IN=/Users/timmerman/Documents/github/googleapis/google-cloudevents/proto/
- OUT=/Users/timmerman/Documents/github/googleapis/google-cloudevents-nodejs/src
- L=TYPESCRIPT
***********************
== START ==
- Finding all JSON Schemas (schema.json)...
Found 2 schema(s).
- LogEntryData                            : …
```
> feat: enable cli flags to quicktype wrapper

- proto/google/events/cloud/pubsub/v1/schema.json
Fixes the json schema for Pub/Sub, key `messageId`.
See: https://cloud.google.com/pubsub/docs/reference/rest/v1/PubsubMessage
Fixes: https://github.com/googleapis/google-cloudevents/issues/64
> fix: fix pub/sub message json schema

- proto/google/events/cloud/audit/v1/LogEntryData.json
- proto/google/events/cloud/pubsub/v1/MessagePublishedData.json
Fixes #66. There were a few mistakes with the JSON Schema (specifically the references). VS Code and JSONSchema editors have nice tooling for go-to-defintion and schema errors.
- Completes JSON Schema descriptions (manually from the proto source – yes this should be automatic at some point)
- Changes indentation to 2 spaces for more standard json indentation (sorry for the poor diff)
- Fixes some of the invalid schema references
Reference errors were detected and fixed with this tool:
https://www.jsonschemavalidator.net/
---
This should give better IDE descriptions. Will work on patching the QuickType wrapper in parallel to this.
> feat: update JSON Schema descriptions and references

- jsonschema/google/events/cloud/audit/v1/LogEntryData.json
Modifies the JSON Schema field keys to use camelCase as provided by the Eventarc API, but not the representation used in protos.
See:
- go/proto3-json-spec
- https://developers.google.com/protocol-buffers/docs/proto3#json_options
> fix: change cal jsonschema to use camelCase

- tools/quicktype-wrapper/src/index.ts
- tools/quicktype-wrapper/src/quickstype.ts
Fixes: https://github.com/googleapis/google-cloudevents/issues/83 – needed for Java
- Supports multi-file type exports (every language runs through the more generic `quicktypeMultiFile` function now)
- Preserves single file type exports.
- Slightly improves comments
- Slightly improves output
I don't think many languages require this (only `java` and `objective-c` from what I can tell).
Java:
```sh
qt \
--in=~/Documents/google-cloudevents/jsonschema/google/events/ \
--out=~/Documents/trash/testqt \
--l=java
***********************
** Quicktype Wrapper **
***********************
* Valid Languages (L): csharp,java,python,rust,crystal,ruby,golang,cplusplus,elm,swift,objective-c,typescript,javascript,kotlin,dart,pike,haskell
***********************
* Config:
- …
```
> feat: support multi-file exports for qt

- tools/quicktype-wrapper/README.md
- tools/quicktype-wrapper/src/index.ts
- tools/quicktype-wrapper/src/license.ts
- tools/quicktype-wrapper/src/quickstype.ts
Per request, adds option to add license headers to generated files.
Fixes: https://github.com/googleapis/google-cloudevents/issues/88
> feat: qt enable headers flag

- jsonschema/google/events/cloud/audit/v1/LogEntryData.json
- jsonschema/google/events/cloud/cloudbuild/v1/BuildEventData.json
- jsonschema/google/events/cloud/firestore/v1/DocumentEventData.json
- jsonschema/google/events/firebase/analytics/v1/AnalyticsLogData.json
- jsonschema/google/events/firebase/auth/v1/AuthEventData.json
- tools/proto2jsonschema/postgen.js
- Fixes some schemas which generate `$ref` keys that are invalid. Adds a TODO to see if the crusty generator can fix this instead.
- Affects some events.
- Deletes not-so-useful non-top-level `$schema` attributes.
Tested schema links locally.
> fix: update jsonschema ref urls

- tools/quicktype-wrapper/package-lock.json
- tools/quicktype-wrapper/src/index.ts
- tools/quicktype-wrapper/src/license.ts
- tools/quicktype-wrapper/src/quickstype.ts
- Uses the common license header with the correct 
- Some languages do not support `//` comments
- Based on https://github.com/google/addlicense/tree/master/testdata/expected with additional languages added.
---
Yoshi Java warns if single-line comments are used for the header:
- https://github.com/googleapis/google-cloudevents-java/issues/24
> fix: use dynamic license header characters per language

- tools/quicktype-wrapper/src/index.ts
- Fixes the qt path output for single-file outputs. The current output has "stdout" in the path, which isn't what we want.
- Makes the output a bit more pretty
Tested with Node and Go:
```
***********************
** Quicktype Wrapper **
***********************
* Valid Languages (L): csharp,java,python,rust,crystal,ruby,golang,cplusplus,elm,swift,objective-c,typescript,javascript,kotlin,dart,pike,haskell
***********************
* Config:
- IN=/Users/timmerman/Documents/github/googleapis/google-cloudevents/jsonschema
- OUT=/Users/timmerman/Documents/github/googleapis/google-cloudevents-go
- L=GOLANG
***********************
== START ==
- Finding all JSON Schemas (*.json)...
Found 10 schema(s):
- /google/events/cloud/audit/v1/LogEntryData.json
- …
```
> fix: update qt single-out filename

- README.md
- tools/registry/Google.Events.Tools.GenerateRegistry/Program.cs
Fixes #67
- Adds Product name column
- These human-readable product name are not structurally defined in protos
- Exact spelling pulled from product pages
- README table generator throws exception when trying to gen with an unknown package
- Updates comments around column numbers. The ordering of columns is not imperative and can be changed.
> docs: add cloudevent product name column

- jsonschema/google/events/cloud/cloudbuild/v1/BuildEventData.json
- jsonschema/google/events/cloud/firestore/v1/DocumentEventData.json
- jsonschema/google/events/firebase/analytics/v1/AnalyticsLogData.json
- tools/proto2jsonschema/gen.sh
- tools/proto2jsonschema/postgen.js
Simplifies the `$ref` identifiers.
- The name is used by some generators like **Java**, causing really ugly Java POJO names.
- Example: `googleEventsCloudCloudbuildV1TimeSpan` -> `TimeSpan`
- Runs the generator
I suppose this could be an upstream feature of crusty at some point.
> feat: simplify jsonschema ref names in postgen

- tools/quicktype-wrapper/src/index.ts
Generates the correct filename (from JSON Schema) in the quicktype wrapper.
Most languages use `MyLangNoModification.EXT`, but Go uses `my_lang_no_modification.EXT`. May add other languages later.
Related: https://github.com/googleapis/google-cloudevents-go/pull/16
> feat: gen snake_case filenames for golang

- jsonschema/google/events/cloud/audit/v1/LogEntryData.json
- jsonschema/google/events/cloud/cloudbuild/v1/BuildEventData.json
- jsonschema/google/events/cloud/firestore/v1/DocumentEventData.json
- jsonschema/google/events/cloud/pubsub/v1/MessagePublishedData.json
- jsonschema/google/events/cloud/scheduler/v1/SchedulerJobData.json
- jsonschema/google/events/cloud/storage/v1/StorageObjectData.json
- jsonschema/google/events/firebase/analytics/v1/AnalyticsLogData.json
- jsonschema/google/events/firebase/auth/v1/AuthEventData.json
- jsonschema/google/events/firebase/database/v1/ReferenceEventData.json
- jsonschema/google/events/firebase/remoteconfig/v1/RemoteConfigEventData.json
- tools/README.md
- tools/proto2jsonschema/package-lock.json
- tools/proto2jsonschema/package.json
- tools/proto2jsonschema/postgen.js
- Enhances CloudEvent JSON schemas with `package`, `datatype`, and `types` fields. Data is from protos as source of truth still.
- Implements part 1 of 2 for design doc "Proposal: Augment JSON Schemas".
- Updates README.
---
Part 2 will be to create the JSON schema registry.
> feat: enhances jsonschema

- jsonschema/catalog.json
- tools/jsonschema-catalog/.gitignore
- tools/jsonschema-catalog/README.md
- tools/jsonschema-catalog/index.js
- tools/jsonschema-catalog/package-lock.json
- tools/jsonschema-catalog/package.json
Adds JSON schema catalog/registry
- Implements part 2 of 2 for design doc "Proposal: CloudEvent JSON Schema Registry".
- Note: Catalog entries will be updated (and a bit more complete) when jsonschema enhancements are in: https://github.com/googleapis/google-cloudevents/pull/112
> feat: init jsonschema catalog

- proto/google/events/cloud/audit/v1/data.proto
- proto/google/events/cloud/cloudbuild/v1/data.proto
- proto/google/events/cloud/pubsub/v1/data.proto
- proto/google/events/firebase/auth/v1/data.proto
Reviews all data.proto descriptions. These descriptions are used in the JSON schemas and client libraries.
Fixes https://github.com/googleapis/google-cloudevents/issues/118
> fix: standardize data proto descriptions

- jsonschema/google/events/cloud/audit/v1/LogEntryData.json
- jsonschema/google/events/cloud/cloudbuild/v1/BuildEventData.json
- jsonschema/google/events/cloud/firestore/v1/DocumentEventData.json
- jsonschema/google/events/cloud/storage/v1/StorageObjectData.json
- jsonschema/google/events/firebase/analytics/v1/AnalyticsLogData.json
- jsonschema/google/events/firebase/remoteconfig/v1/RemoteConfigEventData.json
- tools/proto2jsonschema/gen.sh
Uses `type: string` for proto `int64` (and related (`*64`) types per [proto JSON representation spec](https://developers.google.com/protocol-buffers/docs/proto3#json).
This is causing an issue in the golang from jsonschema generator: https://github.com/googleapis/google-cloudevents-go/issues/22
---
I used the master branch of the `protoc-gen-jsonschema` tool to get this fix.
See issue: https://github.com/chrusty/protoc-gen-jsonschema/issues/47
> fix: remove oneof type for 64 bit numbers

- .github/workflows/generate.yaml
Fixes the CI git diff check.
Runs the generator and diff in the same CI job.
They cannot be run in parallel, it must be sequential (gen then diff).
CI should purposefully fail due to https://github.com/googleapis/google-cloudevents/issues/126.
> ci: run build and git diff in same github workflow job

- jsonschema/google/events/cloud/audit/v1/LogEntryData.json
- jsonschema/google/events/cloud/cloudbuild/v1/BuildEventData.json
- jsonschema/google/events/cloud/firestore/v1/DocumentEventData.json
- jsonschema/google/events/cloud/pubsub/v1/MessagePublishedData.json
- jsonschema/google/events/cloud/scheduler/v1/SchedulerJobData.json
- jsonschema/google/events/cloud/storage/v1/StorageObjectData.json
- jsonschema/google/events/firebase/analytics/v1/AnalyticsLogData.json
- jsonschema/google/events/firebase/auth/v1/AuthEventData.json
- jsonschema/google/events/firebase/database/v1/ReferenceEventData.json
- jsonschema/google/events/firebase/remoteconfig/v1/RemoteConfigEventData.json
- scripts/clean.sh
- scripts/compile.sh
- scripts/gen.sh
- tools/jsonschema-catalog/gen.sh
- tools/proto2jsonschema/gen.sh
- tools/readme-catalog/index.js
Now that we have CI checking that the full generation steps is working, this PR makes the CI pass (through a few adjustments).
- Ensures the chrusty protoc plugin that is specified is fixed
- Ensures anyone running this locally doesn't use a cached version by deleting the cache beforehand.
- Latest crusty plugin has some updates:
- Fixes bad `oneOf` types allowing nulls. https://github.com/chrusty/protoc-gen-jsonschema/commit/7726bafee96859cdee2947f818544b2af809be75
- This is a good thing as having it causes complicated behavior in language clients.
- Fixes enum values per: https://github.com/chrusty/protoc-gen-jsonschema/pull/44
- Slightly adjust output of generator scripts to be more readable and debuggable.
- Adds cleaning script for helping the system packages are correct.
You'll …
> fix: Fix CI. Regen with latest Chrusty plugin.

- tools/quicktype-wrapper/package-lock.json
- tools/quicktype-wrapper/package.json
- tools/quicktype-wrapper/src/index.ts
- tools/quicktype-wrapper/src/quickstype.ts
This PR ensures the JSON schema `catalog.json` file isn't pulled in as a JSON schema input file.
Related: https://github.com/googleapis/google-cloudevents-python/pull/29
> fix: ignore the catalog when running qt

- jsonschema/google/events/firebase/auth/v1/AuthEventData.json
- proto/google/events/firebase/auth/v1/data.proto
This allows them to conform with our API conventions better.
Functions Frameworks will need to perform appropriate conversions.
> Rename fields in Firebase auth UserMetadata message

- testdata/google/events/cloud/pubsub/v1/MessagePublishedData-binary.json
- testdata/google/events/cloud/pubsub/v1/MessagePublishedData-text.json
The value for `publishTime` copied from #151, which contained an
observed payload from Eventarc.
> test: Ensure that both PubSub test events have messageId and publishTime

- .github/workflows/compile.yaml
- .github/workflows/generate.yaml
- .github/workflows/license.yaml
- .github/workflows/validate_clients.yaml
- scripts/clean.sh
- scripts/compile.sh
- scripts/gen.sh
- third_party/googleapis/google/rpc/rpc_publish.yaml
- third_party/googleapis/google/type/type.yaml
- tools/jsonschema-catalog/gen.sh
- tools/jsonschema-catalog/index.js
- tools/proto2jsonschema/gen.sh
- tools/proto2jsonschema/postgen.js
- tools/quicktype-wrapper/.prettierrc.js
- tools/readme-catalog/index.js
Adds licenses and license CI to Google CloudEvents repo.
- Uses https://github.com/google/addlicense
- Generated with:
- `go get -u github.com/google/addlicense`
- `addlicense .`
Fixes https://github.com/googleapis/google-cloudevents/issues/163
Inspiration: https://github.com/googleapis/google-cloudevents/pull/158#discussion_r576588909
> Add Licenses and License CI

- jsonschema/google/events/cloud/audit/v1/LogEntryData.json
- jsonschema/google/events/cloud/cloudbuild/v1/BuildEventData.json
- jsonschema/google/events/cloud/firestore/v1/DocumentEventData.json
- jsonschema/google/events/cloud/pubsub/v1/MessagePublishedData.json
- jsonschema/google/events/cloud/scheduler/v1/SchedulerJobData.json
Runs the generator manually.
The latest change has improvements to metadata about base64 type strings.
Fixes: https://github.com/googleapis/google-cloudevents/issues/174
> chore: run the generator, feb 26, 2021

- AUDIT_CATALOG.md
- README.md
- tools/readme-catalog/README.md
- tools/readme-catalog/common.js
- tools/readme-catalog/gen-audit-catalog.js
- tools/readme-catalog/gen-cloudevent-catalog.js
- tools/readme-catalog/index.js
- tools/readme-catalog/package.json
Creates a catalog of Cloud Audit Log `serviceName` and `methodName` combinations using the audit catalog.
Required for `google.cloud.audit.log.v1.written` type.
- https://github.com/googleapis/google-cloudevents/blob/grant_cal_catalog/AUDIT_CATALOG.md
- https://github.com/googleapis/google-cloudevents/blob/grant_cal_catalog/README.md#google-cloudevent-catalogs
- Creates new file `AUDIT_CATALOG.md`.
- This file is generated from data in `json/audit/service_catalog.json`. Note: that file is sync'd from g3 via copybara.
- Updates top-level `README.md` to link to 2 event catalogs.
- Updates `tools/readme-catalog` tool
- Splits catalog tool to include both the CloudEvent catalog and CAL catalog generators (and re-use common logic)
- Creates index file for running generators
- Create new …
> Cloud Audit Log Catalog

- .github/workflows/copybara.yaml
Fixes copybara CI script. I think there was a missing `\` in the original script. I also went ahead and made it pretty verbose with the head and base branches, as well as formatted the file a tiny bit.
- Tested manually with https://github.com/googleapis/google-cloudevents/pull/190
- Fixes https://github.com/googleapis/google-cloudevents/issues/189
- Example broken CI run: https://github.com/googleapis/google-cloudevents/runs/2179005439?check_suite_focus=true
> ci: update copybara ci so PRs trigger properly

- .github/workflows/copybara.yaml
It turns out the copybara PR CI wasn't running because we mixed up the base and head branches. As a result, some previous runs of the action didn't trigger a PR. Example:
https://github.com/googleapis/google-cloudevents/runs/2188505173?check_suite_focus=true
This change correctly updates the action. Example PR:
https://github.com/googleapis/google-cloudevents/pull/198
---
Aside, as we update the `master` branch mandually, we'll want to keep up the `copybara` branch. We can do this separately.
> ci: fix copybara ci pr

- .github/workflows/gen_pr.yaml
This PR adds a workflow to this repo that creates PRs when a commit lands to `master` (conditionally if the diff contents is non-zero).
Generated PRs are expected to be reviewed by a human and manually merged.
Fixes: https://github.com/googleapis/google-cloudevents/issues/163
**Event:** Push
**Branch:** `master`
**PR commit:**  `feat: run generator (${NOW})"`
**PR contents:** Runs the generator (`./scripts/gen.sh`)
Example PR on a fork: https://github.com/grant/google-cloudevents/pull/4
Updated the GitHub workflow with the correct information:
- event (push to `master`)
- generator setup (same as compile CI setup)
- generator step (same as diff CI setup)
- git diff conditional (`git status --porcelain`)
- git configs
- unique git branch
- git commit message
- GitHub PR title and body
- Do …
> ci: add PR generator workflow

- tools/quicktype-wrapper/package-lock.json
- tools/quicktype-wrapper/package.json
- tools/quicktype-wrapper/src/quickstype.ts
This minor PR helps support Dart code generation.
This tool (qt) is a tool that generates Google CloudEvent libraries given a schema.
It's used for generating libraries like:
- https://github.com/googleapis/google-cloudevents-nodejs
- https://github.com/googleapis/google-cloudevents-go
- https://github.com/googleapis/google-cloudevents-java
Eventually, we could create a library like http://github.com/googleapis/google-cloudevents-dart (does not exist)
- Updates the `quicktype-wrapper` generator to support better Dart code generation
- See https://github.com/GoogleCloudPlatform/functions-framework-dart/issues/239
- Runs a `npm i` on `quicktype-wrapper`.
> Enable Dart parsing methods for qt generator

- tools/quicktype-wrapper/README.md
- tools/quicktype-wrapper/src/index.ts
Adds option for qt generator to treat enums as strings for client library conversion.
This enables clients to generate without using the JSON schema `oneOf` type, which we want to preserve semantically, but can cause issues with clients actually parsing JSON, which is a string, not a oneOf string|int.
This feature is required for fixing the golang client:
- See https://github.com/googleapis/google-cloudevents-go/issues/68
> feat: Add enum to string option for qt

- README.md
This stability is restricted to just the protos, and only those on
the default branch.
cc @hrasadi and @haolicopter (who should probably have more rights on this repo)
> Declare the protos on the default branch to be stable

- jsonschema/google/events/cloud/audit/v1/LogEntryData.json
- jsonschema/google/events/cloud/cloudbuild/v1/BuildEventData.json
- jsonschema/google/events/cloud/firestore/v1/DocumentEventData.json
- jsonschema/google/events/cloud/pubsub/v1/MessagePublishedData.json
- jsonschema/google/events/cloud/scheduler/v1/SchedulerJobData.json
- jsonschema/google/events/firebase/auth/v1/AuthEventData.json
- jsonschema/google/events/firebase/database/v1/ReferenceEventData.json
- tools/proto2jsonschema/gen.sh
Fixes https://github.com/googleapis/google-cloudevents/issues/250
Uses `PROTOC_PLUGIN_VERSION=1.0.0`.
- Better JSON representation for `google.protobuf.Value`
- Better JSON representation for `google.protobuf.Duration`
This should result in better parsing for these well known types, and types that aren't always JSON objects (hence the oneOf).
See: https://developers.google.com/protocol-buffers/docs/reference/google.protobuf
- e.g. https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Value
Gen'd updates to language clients would follow this PR. Unfortunately the `oneOf` syntax isn't the greatest with quicktype. Although it is the most accurate for the JSON (not everything is an object), and easier to deal with downstream. Look at the protobuf docs …
> feat: improve jsonschema types for protobuf well known types

- .github/workflows/copybara.yaml
Fix base naming branch (from `master` to `main`) in the copybara workflow (creating a copybara PR).
> Fix base naming branch in copybara workflow

- .github/workflows/generate.yaml
The `generate` workflow runs for any `push` or any `pull request` action and makes sure no changes have been introduced to the proto schemas.
The problem is that `copybara` branch might in fact be performing changes to those schemas (eg: adding a new one), thus making it fail, and not allowing admins to merge it without disabling branch protection first.
I'm proposing to skip this workflow for the `copybara` branch to reduce manual intervention.
FYI, once a `copybara` PR is submitted to `main`, the generator will run anyway and create a PR with any new changes.
> Exclude copybara branch from the Generate workflow

- tools/proto2jsonschema/postgen.js
If we don't do this, then all JSON schemas get associated with every event type defined in events.proto. But those events might not all have the same payload.
For example before this change, with the following events defined in the same events.proto file:
```proto
message FooEvent {
option (google.events.cloud_event_type) = "google.example.foo.v1.blah";
FooEventData data = 1;
}
message BarEvent {
option (google.events.cloud_event_type) = "google.example.bar.v1.blah";
BarEventData data = 1;
}
```
The schemas would look like:
```json
{
"name": "FooEventData",
"cloudeventTypes": [
"google.example.bar.v1.blah",
"google.example.foo.v1.blah"
]
}
```
```json
{
"name": "BarEventData",
"cloudeventTypes": [
"google.example.bar.v1.blah",
"google.example.foo.v1.blah"
]
}
```
This change makes sure …
> Fetch CloudEvent type only for matching payload types

- .github/workflows/validate_clients.yaml
This should fix the .NET failure in #378.
> chore: Use .NET 6 instead of .NET Core 3.1 for .NET validation

- scripts/compile.sh
- tools/proto2jsonschema/gen.sh
This is the minimum requirement go get the cloud IOT events building
again (as 3.15 eliminated the need for the
--experimental__allow_proto3_optional flag
> deps: update protobuf version to 3.15.0

- .github/CODEOWNERS
With this change, I propose we scope cloudevent-admins to the Eventarc team. This will prevent others from approving copybara PRs without a review from the Eventarc team.
> refactor: Update CODEOWNERS

- .github/CODEOWNERS
Fixes #427. I've created a new GitHub TeamSync group [eventarc-team](https://github.com/orgs/googleapis/teams/eventarc-team) which is linked to the Eventarc mdb group.
The proposed changes here are to only allow Eventarc team members to approve changes in the copybara directories.
> chore: update CODEOWNERS - eventarc-team owner of copybara directories

- .github/workflows/test_clients.yaml
* Adds Go to test client workflow
* Limits workflow permission to `contents: read` for .NET, Java, and Go
> testing: add go to test-client workflow

- .github/workflows/check_unexpected_changes.yaml
- .github/workflows/generate_jsonschema/action.yaml
- .github/workflows/test_jsonschemas.yaml
The JSON schema generation is causing a new package-lock.json to be generated. Upgrading the node version hopefully will stop that from happening. The "fix" of only checking for changes in the jsonschema/ directory should not be needed anymore.
> chore: update node version

- .github/workflows/test_clients.yaml
The Go version in place was go 1.19. This change updates to use the latest patch release of go 1.23. This seems like it may address the build errors such as "google.golang.org/protobuf/internal/flags: cannot compile Go 1.22 code"
I would like to separate investigating the failing .NET and Java tests.
The unexpected changes check is failing because the protos have been updated, but the JSON Schema has not yet been updated. I am holding off on updating that until we see the tests passing based on the current state of the protos.
I would like to have a code review and required checks rules bypass merge to make this change despite the other failing tests.
> chore(deps): Update go version for go client smoke test

- .github/workflows/test_clients.yaml
This is a .NET equivalent of a problem similar to #632. Depending on the order in which broken checks are resolved, this may also require an admin merge to bypass required checks.
According to the logs for a failing smoke test at https://github.com/googleapis/google-cloudevents/actions/runs/14789546588/job/41523929026,
> Install the [8.0.408] .NET SDK or update [/home/runner/work/google-cloudevents/google-cloudevents/google-cloudevents-dotnet/global.json] to match an installed SDK.
I am not familiar with .NET runtimes but trying a naive update of the number to see what happens.
> chore(deps): Update .NET version for .NET client smoke test #
