googleapis/google-cloudevents

proto/google/events/cloud/storage/v1/events.proto

Ref: https://github.com/googleapis/google-cloudevents/issues/6

Make storage crc32c hash a string

---

proto/google/events/cloud/pubsub/v1/events.proto

Will file an issue to create a Travis build that validates the protos.

Fix PubSub proto (message rename was incomplete)

---

proto/google/events/firebase/v1/events.proto

(These are deliberately not in a "cloud" directory, and so "cloud" shouldn't be in the event type.)
@grant: Apologies for the deluge of tiny PRs today!

Fix Firebase event types

---

.gitignore
.travis.yml
README.md
compile.sh
generate-event-registry.sh
tools/Google.Events.Tools.GenerateRegistry/Google.Events.Tools.GenerateRegistry.csproj
tools/Google.Events.Tools.GenerateRegistry/Program.cs
tools/Google.Events.Tools.sln
tools/README.md
travis.sh

This is very drafty - it's just the *kind* of thing we can do.
Sample output:
```text
google.cloud.audit.log.v1.written:
Event message: google.events.cloud.audit.v1.AuditLogWrittenEvent
Data message: google.events.cloud.audit.v1.AuditLogData
google.cloud.firestore.document.v1.created:
Event message: google.events.cloud.firestore.v1.DocumentCreatedEvent
Data message: google.events.cloud.firestore.v1.DocumentEventData
google.cloud.firestore.document.v1.updated:
Event message: google.events.cloud.firestore.v1.DocumentUpdatedEvent
Data message: google.events.cloud.firestore.v1.DocumentEventData
google.cloud.firestore.document.v1.deleted:
Event message: google.events.cloud.firestore.v1.DocumentDeletedEvent
Data message: google.events.cloud.firestore.v1.DocumentEventData …
```

Event registry generation tool

---

README.md

Cross links the various language repos.

docs: add link to type repos

---

README.md

Reserve H1s for document titles, H2 for section titles

docs: readme titles

---

proto/google/events/cloud/audit/v1/data.proto

This reflects the changes in the [googleapis
commit](https://github.com/googleapis/googleapis/commit/40292fc8f271f3b8708f9c91c85d7240200893a6).
Fixes most of the discrepancies noted in #43.

Update AuditLogData based on googleapis

---

proto/google/events/cloud/audit/v1/schema.json
proto/google/events/cloud/pubsub/v1/schema.json

Adds descriptions for many fields in the JSON Schemas for better IDE results. Descriptions pulled from protos/docs.
Not comprehensive.

feat: add descriptions to main jsonschema fields

---

tools/quicktype-wrapper/src/index.ts

- Added a utility method for code generation in languages other than Javascript (Node.js)/Typescript
- Made sure than the main method runs only when the package is called directly

Updated the quicktype-wrapper package

---

tools/quicktype-wrapper/src/license.ts

Small mistake with license header.

fix: use https with license

---

.gitignore
proto/google/events/cloud/audit/v1/events.proto
proto/google/events/cloud/cloudbuild/v1/events.proto
proto/google/events/cloud/firestore/v1/events.proto
proto/google/events/cloud/pubsub/v1/events.proto
proto/google/events/cloud/scheduler/v1/events.proto
proto/google/events/cloud/storage/v1/events.proto
proto/google/events/cloudevent.proto
proto/google/events/firebase/analytics/v1/events.proto
proto/google/events/firebase/auth/v1/events.proto
proto/google/events/firebase/database/v1/events.proto
proto/google/events/firebase/remoteconfig/v1/events.proto
tools/registry/Google.Events.Tools.GenerateRegistry/Program.cs

(I'm aware we may want to ditch the .NET registry generator when your other registry-oriented work is complete, but it's good to keep it up-to-date for now. Alternatively, I'd be happy to change the generator to perform the schema augmentation if that would make things simpler.)

Include the product name in protos

---

jsonschema/catalog.json
jsonschema/google/events/cloud/audit/v1/LogEntryData.json
jsonschema/google/events/cloud/cloudbuild/v1/BuildEventData.json
jsonschema/google/events/cloud/pubsub/v1/MessagePublishedData.json
jsonschema/google/events/firebase/auth/v1/AuthEventData.json

Generates JSON schemas from updated proto descriptions.
See proto PR: https://github.com/googleapis/google-cloudevents/pull/120

chore: update jsonschemas from protos

---

json/audit/service_catalog.json

Manually adding json/audit/service_catalog.json for Audit Log events.

Create service_catalog.json for Audit Log Events

---

jsonschema/google/events/cloud/audit/v1/LogEntryData.json
jsonschema/google/events/firebase/remoteconfig/v1/RemoteConfigEventData.json

Manually runs build after copybara change (we'll need to automate this).

ci: fix build

---

tools/readme-catalog/common.js
tools/readme-catalog/gen-audit-catalog.js
tools/readme-catalog/gen-cloudevent-catalog.js

Adds licenses to various files.
Fixes license CI check.

chore: add licenses to files

---

tools/proto2jsonschema/postgen.js

fix: Fix generation on Windows

---

.github/workflows/copybara.yaml
.github/workflows/validate_jsonschemas.yaml
AUDIT_CATALOG.md
README.md
jsonschema/google/events/cloud/audit/v1/LogEntryData.json
jsonschema/google/events/cloud/cloudbuild/v1/BuildEventData.json
jsonschema/google/events/cloud/firestore/v1/DocumentEventData.json
jsonschema/google/events/cloud/pubsub/v1/MessagePublishedData.json
jsonschema/google/events/cloud/scheduler/v1/SchedulerJobData.json
jsonschema/google/events/cloud/storage/v1/StorageObjectData.json
jsonschema/google/events/firebase/auth/v1/AuthEventData.json
scripts/validate_jsonschema.sh
tools/proto2jsonschema/gen.sh
tools/proto2jsonschema/package-lock.json
tools/proto2jsonschema/package.json
tools/proto2jsonschema/postgen.js
tools/quicktype-wrapper/package-lock.json
tools/readme-catalog/README.md
tools/readme-catalog/common.js
tools/readme-catalog/gen-audit-catalog.js
tools/readme-catalog/gen-cloudevent-catalog.js
tools/readme-catalog/index.js
tools/readme-catalog/package.json

Keep copybara branch updated so that it has the latest GitHub action script and CloudEvent-related changes.

Update copybara branch

---

.github/workflows/copybara.yaml
.github/workflows/validate_jsonschemas.yaml
AUDIT_CATALOG.md
README.md
jsonschema/google/events/cloud/audit/v1/LogEntryData.json
jsonschema/google/events/cloud/cloudbuild/v1/BuildEventData.json
jsonschema/google/events/cloud/firestore/v1/DocumentEventData.json
jsonschema/google/events/cloud/pubsub/v1/MessagePublishedData.json
jsonschema/google/events/cloud/scheduler/v1/SchedulerJobData.json
jsonschema/google/events/cloud/storage/v1/StorageObjectData.json
jsonschema/google/events/firebase/auth/v1/AuthEventData.json
scripts/validate_jsonschema.sh
tools/proto2jsonschema/gen.sh
tools/proto2jsonschema/package-lock.json
tools/proto2jsonschema/package.json
tools/proto2jsonschema/postgen.js
tools/quicktype-wrapper/package-lock.json
tools/readme-catalog/README.md
tools/readme-catalog/common.js
tools/readme-catalog/gen-audit-catalog.js
tools/readme-catalog/gen-cloudevent-catalog.js
tools/readme-catalog/index.js
tools/readme-catalog/package.json

Updates the copybara branch with the latest from master.
I'm not sure how the copybara branch doesn't have these updates.
Currently the branch is: 4 commits ahead, 8 commits behind master.
---
After this PR, we'll need a PR to update master with the 4 copybara commits.

Update copybara branch with latest master

---

.github/workflows/copybara.yaml
.github/workflows/validate_jsonschemas.yaml
AUDIT_CATALOG.md
README.md
jsonschema/google/events/cloud/audit/v1/LogEntryData.json
jsonschema/google/events/cloud/cloudbuild/v1/BuildEventData.json
jsonschema/google/events/cloud/firestore/v1/DocumentEventData.json
jsonschema/google/events/cloud/pubsub/v1/MessagePublishedData.json
jsonschema/google/events/cloud/scheduler/v1/SchedulerJobData.json
jsonschema/google/events/cloud/storage/v1/StorageObjectData.json
jsonschema/google/events/firebase/auth/v1/AuthEventData.json
scripts/validate_jsonschema.sh
tools/proto2jsonschema/gen.sh
tools/proto2jsonschema/package-lock.json
tools/proto2jsonschema/package.json
tools/proto2jsonschema/postgen.js
tools/quicktype-wrapper/package-lock.json
tools/readme-catalog/README.md
tools/readme-catalog/common.js
tools/readme-catalog/gen-audit-catalog.js
tools/readme-catalog/gen-cloudevent-catalog.js
tools/readme-catalog/index.js
tools/readme-catalog/package.json

Try # 2 for updating the `copybara` branch. I'll be sure to not squash when merging.

Merge Master Into Copybara

---

.github/release-please.yml

Enables release please on this repo to enable simple releasing.

chore: init release please

---

tools/quicktype-wrapper/package-lock.json

Updates the tools/quicktype-wrapper package lock to version 2.

chore: update qt package-lock

---

AUDIT_CATALOG.md

feat: run generator (03-24-2022)

---

proto/google/events/firebase/firebasealerts/v1/cloud_event_payload.proto

Fixing minor typos in the comments.

Fixing minor typos in comments

---

.github/header-checker-lint.yml

Adding app config and removing license workflow in PR #408

refactor: add header checker lint app config

---

json/audit/service_catalog.json

Updated service catalog for December 9, 2022

Updated service catalog for December 9, 2022
